#!/bin/sh
#######################################################
#
# Description:
#   Store the temperature value to the database
# Last modified: 2013-01-02
#
#######################################################

VALUE=$1 # Have possibility to import the value as an argument
SQLITE="`which sqlite3`"
DIR="${0%/*}"
DSN="$DIR/temperature.db"
GET_TEMP=$DIR/w1-temp

if [ -z "$SQLITE" ]; then
    echo "SQLite not found. Exiting"
    exit 1
fi
if [ ! -f $DSN ]; then
    echo "Database does not exist. Creating it."
    echo "
        PRAGMA foreign_keys = ON;
        CREATE TABLE locations(
          location_id INTEGER PRIMARY KEY NOT NULL,
          location VARCHAR(50));
        CREATE TABLE temperatures(
          temp_id INTEGER PRIMARY KEY NOT NULL,
          location_id integer,
          value FLOAT NOT NULL,
          created DATETIME NOT NULL,
          FOREIGN KEY(location_id) REFERENCES locations(location_id));
        CREATE INDEX idx1_temperatures ON temperatures (created);
        " | $SQLITE $DSN
fi

if [ -z "$VALUE" ]; then
    VALUE=`$GET_TEMP`
fi

$SQLITE $DSN "INSERT INTO temperatures(temp_id, location_id, value, created) \
    VALUES (NULL, NULL, $VALUE, datetime('now','localtime'))"

#$SQLITE $DSN "select * from temperatures"
#echo $VALUE

exit 0
