#!/bin/sh
#######################################################
#
# Description:
#   Store the temperature value to the database
# Last modified: 2012-12-31
#
#######################################################

VALUE=$1 # Have possibility to import the value as an argument
SQLITE="`which sqlite3`"
DIR="${0%/*}"
DSN="$DIR/temperature.db"
GET_TEMP=$DIR/w1-temp

if [ -z "$SQLITE" ]; then
    echo "SQLite not found. Exiting"
    exit 1
fi
if [ ! -f $DSN ]; then
    echo "Database does not exist. Creating it."
    $SQLITE $DSN "CREATE TABLE temperatures(temp_id INTEGER PRIMARY KEY NOT NULL, location VARCHAR(50), value FLOAT NOT NULL, created DATETIME NOT NULL)"
    $SQLITE $DSN "CREATE INDEX idx1_temperatures ON temperatures (created)"
fi

if [ -z "$VALUE" ]; then
    VALUE=`$GET_TEMP`
fi

$SQLITE $DSN "INSERT INTO temperatures(temp_id, location, value, created) \
    VALUES (NULL, NULL, $VALUE, datetime('now','localtime'))"

#$SQLITE $DSN "select * from temperatures"
#echo $VALUE

exit 0
