#!/bin/sh
#######################################################
#
# Description:
#   Read value from One Wire DC18B20 temperature sensor
#
# Last modified: 2012-12-30
#
#######################################################

SENSORID="28-0000047a8785" # Unique sensor ID
MIN=12 # Minimum allowed temperature
MAX=30 # Maximum allowed temperature


SENSOR="/sys/bus/w1/devices/$SENSORID/w1_slave"

if [ ! -f "$SENSOR" ]; then
    echo Sensor not found
    exit 1
fi

i=1
CRC=NO
while [ $i -le 10 -a $CRC="NO" ]; do
    DATA=`cat $SENSOR`
    #echo $DATA
    CRC=`echo $DATA|awk '(NR == 1) {print $12}'`
    #echo $CRC
    if [ $CRC = "NO" ]; then
        sleep 1
        i=$((i+1))
    elif [ $CRC = "YES" ]; then
        VALUE=`echo "$DATA"|awk -F= '(NR == 2 ) {print $2/1000}'`        
        # Another sanity check to make sure we are not getting any mangled values
        ERROR=`echo $VALUE $MIN $MAX| awk '{if ($1 > $3 || $1 < $2) print "ERROR"}'`
        if [ ${ERROR}X = "ERRORX" ]; then
            echo "The temperature $VALUE is not between $MIN and $MAX"    
            sleep 1
            i=$((i+1))
        else
            #echo "We are done here. (i=$i)"
            break
        fi
    else
        echo "Something went badly wrong!"
        exit 1
    fi
    #echo $i
done

echo $VALUE
exit 0
